import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppScreen } from '@/components/Header';
import { Card } from '@/components/Card';
import { useTheme } from '@/contexts/ThemeContext';
import { AuthService } from '@/services/chat';
const posts = [{ title: 'Compartilhe uma conquista', body: 'Conte para sua rede o que está construindo na sua jornada profissional.' }, { title: 'Comunidade em movimento', body: 'Encontre profissionais, atletas e especialistas para ampliar suas conexões.' }];
export default function Feed() { const { colors } = useTheme(); const styles = createStyles(colors); const user = AuthService.active(); if (!user) { router.replace('/'); return null; } return <AppScreen title={`Olá, ${user.name.split(' ')[0]}`} subtitle="Seu feed profissional"><Pressable onPress={() => router.push('/Perfil')}><Card style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{user.name.slice(0, 2).toUpperCase()}</Text></View><View><Text style={styles.name}>{user.name}</Text><Text style={styles.role}>{user.headline}</Text><Text style={styles.action}>Ver perfil →</Text></View></Card></Pressable>{posts.map((post) => <Card key={post.title}><Text style={styles.postTitle}>{post.title}</Text><Text style={styles.body}>{post.body}</Text><View style={styles.actions}><Text style={styles.action}>♡ Curtir</Text><Text style={styles.action}>◌ Comentar</Text></View></Card>)}</AppScreen>; }
const createStyles = (colors: ReturnType<typeof useTheme>['colors']) => StyleSheet.create({ profile: { flexDirection: 'row', gap: 14, alignItems: 'center' }, avatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.accent, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.white, fontWeight: '900' }, name: { color: colors.text, fontSize: 16, fontWeight: '800' }, role: { color: colors.text2, fontSize: 13, marginTop: 3 }, postTitle: { color: colors.text, fontSize: 17, fontWeight: '800', marginBottom: 8 }, body: { color: colors.text2, fontSize: 14, lineHeight: 21 }, actions: { flexDirection: 'row', gap: 22, borderTopWidth: 1, borderColor: colors.border, marginTop: 16, paddingTop: 12 }, action: { color: colors.accent, fontSize: 13, fontWeight: '700' } });
