import { Platform } from 'react-native';

export type AppUser = { id: string; name: string; email: string; password: string; role: 'Atleta' | 'Profissional'; headline: string; location: string; bio: string; sports: string; goals: string; healthDescription: string; avatarUri: string; onboardingComplete: boolean; };
export type Conversation = { id: string; participantIds: [string, string]; updatedAt: string; };
export type ChatMessage = { id: string; conversationId: string; senderId: string; text: string; createdAt: string; readAt?: string; };
type Database = { users: AppUser[]; conversations: Conversation[]; messages: ChatMessage[] };
const KEY = 'nextagon-community-db-v1'; const SESSION_KEY = 'nextagon-active-user-id';
let memory: Database = { users: [], conversations: [], messages: [] }; let activeUser: AppUser | null = null;
const webStorage = () => Platform.OS === 'web' && typeof localStorage !== 'undefined' ? localStorage : null;
function database(): Database { const storage = webStorage(); if (!storage) return memory; try { const stored = JSON.parse(storage.getItem(KEY) || '{"users":[],"conversations":[],"messages":[]}') as Database; const users = (stored.users || []).filter((user) => !user.id.startsWith('user-test-')).map((user) => ({ sports: '', goals: '', healthDescription: '', avatarUri: '', onboardingComplete: user.onboardingComplete ?? true, ...user })); return { users, conversations: stored.conversations || [], messages: stored.messages || [] }; } catch { return memory; } }
function save(value: Database) { memory = value; webStorage()?.setItem(KEY, JSON.stringify(value)); }
function setActive(user: AppUser | null) { activeUser = user; const storage = webStorage(); if (!storage) return; if (user) storage.setItem(SESSION_KEY, user.id); else storage.removeItem(SESSION_KEY); }
function updateUser(userId: string, patch: Partial<AppUser>) { const db = database(); const users = db.users.map((user) => user.id === userId ? { ...user, ...patch } : user); save({ ...db, users }); const updated = users.find((user) => user.id === userId)!; if (activeUser?.id === userId) setActive(updated); return updated; }

export const AuthService = {
  register(input: Omit<AppUser, 'id' | 'headline' | 'location' | 'bio' | 'sports' | 'goals' | 'healthDescription' | 'avatarUri' | 'onboardingComplete'>) { const db = database(); const email = input.email.trim().toLowerCase(); if (db.users.some((user) => user.email.toLowerCase() === email)) throw new Error('Este e-mail já está cadastrado.'); const user: AppUser = { ...input, email, id: `user-${Date.now()}`, headline: input.role === 'Profissional' ? 'Profissional da comunidade fitness' : 'Membro da comunidade fitness', location: '', bio: '', sports: '', goals: '', healthDescription: '', avatarUri: '', onboardingComplete: false }; save({ ...db, users: [...db.users, user] }); return user; },
  login(email: string, password: string) { const user = database().users.find((item) => item.email.toLowerCase() === email.trim().toLowerCase() && item.password === password); if (!user) throw new Error('E-mail ou senha inválidos.'); setActive(user); return user; },
  active: () => { if (activeUser) return activeUser; const id = webStorage()?.getItem(SESSION_KEY); const user = id ? database().users.find((item) => item.id === id) || null : null; activeUser = user; return user; },
  logout: () => setActive(null), users: () => database().users,
  updateProfile(userId: string, patch: Partial<Pick<AppUser, 'name' | 'headline' | 'location' | 'bio'>>) { return updateUser(userId, patch); },
  updateOnboardingPreferences(userId: string, patch: Pick<AppUser, 'sports' | 'goals' | 'healthDescription'>) { return updateUser(userId, patch); },
  updateAvatar(userId: string, avatarUri: string) { return updateUser(userId, { avatarUri }); },
  completeOnboarding(userId: string) { return updateUser(userId, { onboardingComplete: true }); },
  updatePassword(userId: string, currentPassword: string, newPassword: string) { const user = database().users.find((item) => item.id === userId); if (!user || user.password !== currentPassword) throw new Error('A senha atual está incorreta.'); if (newPassword.length < 6) throw new Error('A nova senha deve ter ao menos 6 caracteres.'); return updateUser(userId, { password: newPassword }); },
  updateEmail(userId: string, email: string, password: string) { const normalizedEmail = email.trim().toLowerCase(); const db = database(); const user = db.users.find((item) => item.id === userId); if (!user || user.password !== password) throw new Error('Informe sua senha atual para confirmar a alteração.'); if (!/^\S+@\S+\.\S+$/.test(normalizedEmail)) throw new Error('Informe um e-mail válido.'); if (db.users.some((item) => item.id !== userId && item.email.toLowerCase() === normalizedEmail)) throw new Error('Este e-mail já está cadastrado.'); return updateUser(userId, { email: normalizedEmail }); },
  resetData() { save({ users: [], conversations: [], messages: [] }); setActive(null); },
};
export const ConversationService = { list(userId: string) { return database().conversations.filter((item) => item.participantIds.includes(userId)).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); }, findOrCreate(userId: string, otherUserId: string) { const db = database(); const found = db.conversations.find((item) => item.participantIds.includes(userId) && item.participantIds.includes(otherUserId)); if (found) return found; const conversation = { id: `conversation-${Date.now()}`, participantIds: [userId, otherUserId] as [string, string], updatedAt: new Date().toISOString() }; save({ ...db, conversations: [...db.conversations, conversation] }); return conversation; } };
export const MessageService = { list(conversationId: string) { return database().messages.filter((item) => item.conversationId === conversationId).sort((a, b) => a.createdAt.localeCompare(b.createdAt)); }, send(conversationId: string, senderId: string, text: string) { const db = database(); const message: ChatMessage = { id: `message-${Date.now()}`, conversationId, senderId, text: text.trim(), createdAt: new Date().toISOString() }; save({ ...db, messages: [...db.messages, message], conversations: db.conversations.map((item) => item.id === conversationId ? { ...item, updatedAt: message.createdAt } : item) }); return message; } };
